http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  ip:
    host: localhost
    paths: "/ip"
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - response-transformer
  - example-policy
pipelines:
  -ip-poc:
    apiEndpoints:
      - ip
    policies:
      - exapmle-policy:
      - proxy:
          - action:
              serviceEndpoint: httpbin
